version: '3.8'

services:
  db:
    image: postgres:15
    container_name: freeschool_db
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - freeschool_network

  backend:
    build: ./backend
    container_name: freeschool_backend
    env_file: .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    ports:
      - "8000:8000"  # Wichtig: Port-Mapping hinzufügen
    depends_on:
      db:
        condition: service_healthy
    networks:
      - freeschool_network
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    env_file: .env
    environment:
      - VITE_API_BASE_URL=https://api.${DOMAIN}
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - freeschool_network

networks:
  freeschool_network:
    driver: bridge

volumes:
  postgres_data: