"""Add is_deleted to Category

Revision ID: 424a105326a0
Revises: ec8224ec9c3f
Create Date: 2025-04-24 12:49:34.008524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '424a105326a0'
down_revision: Union[str, None] = 'ec8224ec9c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('content', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('lesson', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('teacher', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_deleted')
    op.drop_column('teacher', 'is_deleted')
    op.drop_column('lesson', 'is_deleted')
    op.drop_column('content', 'is_deleted')
    op.drop_column('category', 'is_deleted')
    # ### end Alembic commands ###
