"""add colum user password verify

Revision ID: b345934abcab
Revises: dd4086c25486
Create Date: 2025-04-11 11:27:53.033688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b345934abcab'
down_revision: Union[str, None] = 'dd4086c25486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passwordVerify', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'passwordVerify')
    # ### end Alembic commands ###
