"""Lesson.display_order to str

Revision ID: 7165af850166
Revises: 130c28b0b119
Create Date: 2025-10-24 06:49:46.155770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa, sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7165af850166'
down_revision: Union[str, None] = '130c28b0b119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_content_id'), 'content', ['id'], unique=False)
    op.alter_column('lesson', 'display_order',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.create_index(op.f('ix_lesson_id'), 'lesson', ['id'], unique=False)
    op.create_index(op.f('ix_profile_id'), 'profile', ['id'], unique=False)
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_id'), 'teacher', ['id'], unique=False)
    op.drop_constraint('fk_userlessonlink_lesson_id', 'userlessonlink', type_='foreignkey')
    op.drop_constraint('fk_userlessonlink_user_id', 'userlessonlink', type_='foreignkey')
    op.create_foreign_key(None, 'userlessonlink', 'lesson', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'userlessonlink', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_constraint(None, 'userlessonlink', type_='foreignkey')
    op.drop_constraint(None, 'userlessonlink', type_='foreignkey')
    op.create_foreign_key('fk_userlessonlink_user_id', 'userlessonlink', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_userlessonlink_lesson_id', 'userlessonlink', 'lesson', ['lesson_id'], ['id'])
    op.drop_index(op.f('ix_teacher_id'), table_name='teacher')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_index(op.f('ix_profile_id'), table_name='profile')
    op.drop_index(op.f('ix_lesson_id'), table_name='lesson')
    op.alter_column('lesson', 'display_order',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_content_id'), table_name='content')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    # ### end Alembic commands ###
