"""snake_case und deleted_at

Revision ID: a638c6fbb441
Revises: ac9297578322
Create Date: 2025-09-09 14:59:34.857389

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a638c6fbb441'
down_revision: Union[str, None] = 'ac9297578322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('category', 'is_deleted')
    op.add_column('content', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('content', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('content', 'is_deleted')
    op.add_column('lesson', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('lesson', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('lesson', 'is_deleted')
    op.alter_column('lesson', 'order', new_column_name='display_order')
    op.add_column('profile', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('profile', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_profile_id'), 'profile', ['id'], unique=False)
    op.add_column('role', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.add_column('teacher', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('teacher', sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="de"))
    op.drop_column('teacher', 'is_deleted')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'last_login',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=False,
               postgresql_using='to_timestamp(last_login::double precision)')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'last_login',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('users', 'deleted_at')
    op.add_column('teacher', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('teacher', 'language')
    op.drop_column('teacher', 'deleted_at')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_column('role', 'deleted_at')
    op.drop_index(op.f('ix_profile_id'), table_name='profile')
    op.alter_column('profile', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('profile', 'deleted_at')
    op.alter_column('lesson', 'display_order', new_column_name='order')
    op.add_column('lesson', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.alter_column('lesson', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('lesson', 'deleted_at')
    op.add_column('content', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.alter_column('content', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('content', 'deleted_at')
    op.add_column('category', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('category', 'deleted_at')
    # ### end Alembic commands ###
