"""content text infinity

Revision ID: ec8224ec9c3f
Revises: b345934abcab
Create Date: 2025-04-11 12:09:08.993497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ec8224ec9c3f'
down_revision: Union[str, None] = 'b345934abcab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'text',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'text',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
